default:
  image: node:16.16.0

stages:
  - quality
  - build
  - deploy

.yarn:
  before_script:
    - yarn install --immutable

lint:
  extends:
    - .yarn
  stage: quality
  needs: []
  script:
    - yarn lint

typescript:
  extends:
    - .yarn
  stage: quality
  needs: []
  script:
    - yarn types-check

test:
  extends:
    - .yarn
  stage: quality
  needs: []
  script:
    - yarn test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit: coverage/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build:
  extends:
    - .yarn
  stage: build
  script:
    - yarn
    - yarn build

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
