import { Metadata } from "next";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex text-black font-bold justify-around bg-white py-3">
          <Link href="">Home</Link>
          <Link href="">Exercises</Link>
          <Link href="">Blog</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
